language: ruby
rvm:
- 2.2.2
before_script:
- npm install
- npm install -g grunt-cli
- gem install sass
script: npm test
after_success: bash ./scripts/cibuild
branches:
  only:
    - develop
env:
  global:
  - GH_REF: github.com/Vizzuality/GDA-Dashboard.git
  - secure: RsrL2WzBUpErKrxfX4eCTb0MvOpTWM1zVhCdnfZbr3VZuYo+dgDrRwV/EivW14ZfF6MpObhr1R0cAMNXPGxtU39mqN9o4EPFGupRasGUnBpGfinJHnTzr+Y3Xik79aFUwSR91y3JRNV0vANaGVspJa273QoRxj+RBJ45rJkjL24mf5QP1AIJ5W0LVLgs4BRLkxlq1hjxZF48kvCjNto77EM2yPnOwTlKQmdV4n5G3AGmA85LdR5ZRDOmIAQEchtVXdPhq8KkkFV4Zrm09Yhw4QMoSs2AEHSd3IYBpfLJplj0zN+neo9eUmlsMhwmH8AHbG8XITivZJxsaWZcUx8a09K4lRlqEuYNxb7hVvpWv+WDPIWUDk5yEg8PMowVOVLh3uLa9ISmEeSWuPYoovDt6JBTudt/DsKtzKvr0agMuD7dFX2l9s8xN1QEiHlZa7nJ1+nyPcxVPNsFFm5FhHrgX6jIcxmw99HsgKDk/cmZ1h7teGm3wqXEV8Ocsz/Ks/6rpdvZSkAd9LSF5Yzx8rCXGllbCdsZoj+SMEeV7WLtSgnegIFtSunYftwuwPXxMTKE4xsCJ4lbo/suhL3gJd2e5HLAD3ip5h7cRh54MLPCUfAYwXQvN5mTbEASqJnXiLYtmORHn2JOHKa8CekK46Mjb+wZWBrlnC0pOXPNBF51bxU=
notifications:
  slack:
    secure: GGcHK9OEZdHpxcm+HqHwOT8Uuclu9O3bSkYcHetnhnC1Lzn4YgP31Bd1JzWyjRlFjusNI0cA2dLV+Qpk9zVHf7QkJbACAHdDHqOwPtb6im6wvxRcimHDu+hc0nw1mMFF1Kq65aR1qOipSraKLiInRprERHifaovXaRfB7ng0o/ufmxyZKL7nVw6D0VJ15JouNNhdwzgYJ8DjtpyrSdQT8rlVitgawmeexhIa9Eb46peUBSjCMLd2VCp3KfHQcs/tAVZRFpWMcLLzoYJxb+4x8G0Pw5hgzXDh8vX+Pu7R/ztiACSSzuiYENJkiYK8JaAkbkC0iktTHY71W/QdKBxcXaM14GTEevTSer4JhtewvUAoe/XVhgP3tche47nPbPDRwehXq2IeQfF8wukKD7JagY0t0mCpau2TXFGOQMNKhJwNn3452pT1tFSglSohBmnC7LhqCZEWxD43Ol8tiYlwIZd4ynkbWp22qIge15AgItj6X5ULL5R3/D79FNjG16qepytoUdVvCuAQ9+sjLWo6xMTiXHixfM6l6QXLQ5yw7RmBc7cTsz9o4LBOUTx46rdDhfYtsULbSTSmhyQL8HLuEjlDCcmjucjw1Auds558ymrrhVH6SjyUtEOCLD2TMxmrxZ9Pg4B21SFEpp3FUfBBf1out5oaMhc84W1H4isLB3I=
